tunnel: sensual-tunnel
credentials-file: /home/nonroot/.cloudflared/578667df-a96a-40d3-8cd1-d22e41f62aae.json

ingress:
  - hostname: nginx.sensualbyte.com
    service: http://localhost:8080
  - hostname: ecs.sensualbyte.com
    service: http://localhost:8080
  - hostname: "*.ecs.sensualbyte.com"
    service: http://localhost:8080
  # - hostname: ssh.sensualbyte.com
  #   service: tcp://localhost:22
 

  - service: http_status:404
